# RepData_PeerAssessment1

## Loading and preprocessing the data

```{r}
activity <- read.csv(unz("activity.zip","activity.csv"))
    activity$date <- as.character(unlist(activity$date))
    activity$date <- as.Date(unlist(activity$date))
    sumByDate <- aggregate(activity$steps, by=list(date=activity$date), FUN=sum)
    activity$day <- weekdays(activity$date, abbreviate = TRUE)
    activityFilled <- activity
```

## What is mean total number of steps taken per day?

```{r}
    hist(sumByDate$x, xlab = "steps")
    mean(sumByDate$x, na.rm = TRUE)
    median(sumByDate$x, na.rm = TRUE)
```

## What is the average daily activity pattern?

```{r}
meanByInterval <- aggregate(activity$steps, by=list(date=activity$interval), FUN=mean, na.rm = TRUE)
plot(meanByInterval$date, meanByInterval$x, type = "l", xlab = "Interval", ylab = "Steps")
maxSteps <- max(meanByInterval$x)
```

The max steps taken in an interval is `r maxSteps`.  

## Imputing missing values


```{r}
sum(is.na(activity$steps))
activityFilled$steps <- ifelse(is.na(activityFilled$steps) == TRUE, meanByInterval$x[meanByInterval$date %in% activityFilled$interval], activityFilled$steps)
sumBydateFilled <- sumByDate <- aggregate(activityFilled$steps, by=list(date=activityFilled$date), FUN=sum)
hist(sumBydateFilled$x, xlab = "steps", ylab = "number of days")
mean(sumBydateFilled$x, na.rm = TRUE)
median(sumBydateFilled$x, na.rm = TRUE)
```

## Are there differences in activity patterns between weekdays and weekends?

``` {r}
activityFilledWeekdays <- subset(activityFilled, activityFilled$day %in% c("Mon","Tue","Wed","Thu","Fri"))
activityFilledWeekends <- subset(activityFilled, activityFilled$day %in% c("Sat","Sun"))
meanByIntervalWeekdays <- aggregate(activityFilledWeekdays$steps, by=list(date=activityFilledWeekdays$interval), FUN=mean, na.rm = TRUE)
meanByIntervalWeekends <- aggregate(activityFilledWeekends$steps, by=list(date=activityFilledWeekends$interval), FUN=mean, na.rm = TRUE)
par(mfrow = c(2,1))
plot(meanByIntervalWeekends$date, meanByIntervalWeekends$x, type = "l",xlab = "Interval", ylab = "Steps", main = "Weekends")
plot(meanByIntervalWeekdays$date, meanByIntervalWeekdays$x, type = "l",xlab = "Interval", ylab = "Steps", main = "Weekdays")
```